from lib.htd_validate.htd_validate.validators.td import TreeDecompositionValidator
from lib.htd_validate.htd_validate.validators.ghtd import GeneralizedHypertreeDecompositionValidator
from lib.htd_validate.htd_validate.validators.htd import HypertreeDecompositionValidator
from lib.htd_validate.htd_validate.validators.fhtd import FractionalHypertreeDecompositionValidator
#from auto import AutoDecompositionValidator
